[profile.default]
optimizer = true
optimizer_runs = 200
src = "contracts"
test = "test"
out = "out"
libs = ["node_modules", "lib"]

[profile.remappings]
"@openzeppelin/"="node_modules/@openzeppelin/"
"hardhat/"="node_modules/hardhat/"
"forge-std/"="lib/forge-std/src/"
