[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["node_modules", "lib"]

[remappings]
"@openzeppelin/"="node_modules/@openzeppelin/"
"hardhat/"="node_modules/hardhat/"
"forge-std/"="lib/forge-std/src/"
